import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'dart:convert';
import '../models/note.dart';

class DatabaseHelper {
  static final DatabaseHelper instance = DatabaseHelper._init();
  static Database? _database;

  DatabaseHelper._init();

  Future<Database> get database async {
    if (_database != null) return _database!;
    _database = await _initDB('notes.db');
    return _database!;
  }

  Future<Database> _initDB(String filePath) async {
    final dbPath = await getDatabasesPath();
    final path = join(dbPath, filePath);

    return await openDatabase(path, version: 1, onCreate: _createDB);
  }

  Future<void> _createDB(Database db, int version) async {
    await db.execute('''
CREATE TABLE notes (
  timestamp INTEGER NOT NULL,
  data TEXT NOT NULL,
  service TEXT NOT NULL,
  overview TEXT NOT NULL,
  image TEXT
)
    ''');
  }

  Future<int> create(Note note) async {
    final db = await instance.database;
    final map = {
      'timestamp': note.timestamp,
      'data': jsonEncode(note.data),
      'service': note.service,
      'overview': note.overview,
      'image': note.image,
    };
    return await db.insert('notes', map);
  }

  Future<List<Note>> readAllNotes() async {
    final db = await instance.database;

    final orderBy = 'timestamp DESC';
    final result = await db.query('notes', orderBy: orderBy);

    return result.map((json) {
      final timestamp = json['timestamp'] as int;
      final service = json['service'] as String;

      return Note(
        timestamp: timestamp,
        data: jsonDecode(json['data'] as String),
        service: service,
        overview: json['overview'] as String,
        image: json['image'] as String?,
        // ID is not stored, so it will be auto-generated by constructor: '${timestamp}_$service'
        // or we can use rowid if we select it?
        // For now, let's respect the user's column list strictly.
      );
    }).toList();
  }

  Future<int> deleteOld(bool deleteOldData) async {
    // Implementation depends on requirements, for now simple delete all if needed
    // or delete based on timestamp
    return 0;
  }

  Future<void> deleteAll() async {
    final db = await instance.database;
    await db.delete('notes');
  }

  Future<void> deleteByService(String service) async {
    final db = await instance.database;
    await db.delete('notes', where: 'service = ?', whereArgs: [service]);
  }

  Future<void> insertBatch(List<Note> notes) async {
    final db = await instance.database;
    final batch = db.batch();
    for (var note in notes) {
      final map = {
        'timestamp': note.timestamp,
        'data': jsonEncode(note.data),
        'service': note.service,
        'overview': note.overview,
        'image': note.image,
      };
      batch.insert('notes', map);
    }
    await batch.commit(noResult: true);
  }

  Future<void> deleteWhere(String where, List<Object?> whereArgs) async {
    final db = await instance.database;
    await db.delete('notes', where: where, whereArgs: whereArgs);
  }
}
