import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'dart:convert';
import '../models/note.dart';

class DatabaseHelper {
  static final DatabaseHelper instance = DatabaseHelper._init();
  static Database? _database;

  DatabaseHelper._init();

  Future<Database> get database async {
    if (_database != null) return _database!;
    _database = await _initDB('notes.db');
    return _database!;
  }

  Future<Database> _initDB(String filePath) async {
    final dbPath = await getDatabasesPath();
    final path = join(dbPath, filePath);

    return await openDatabase(
      path,
      version: 2,
      onCreate: _createDB,
      onUpgrade: _onUpgrade,
    );
  }

  Future<void> _createDB(Database db, int version) async {
    await db.execute('''
CREATE TABLE notes (
  timestamp INTEGER NOT NULL,
  data TEXT NOT NULL,
  service TEXT NOT NULL,
  overview TEXT NOT NULL,
  image TEXT
)
    ''');
    _createImageCacheTable(db);
  }

  Future<void> _onUpgrade(Database db, int oldVersion, int newVersion) async {
    if (oldVersion < 2) {
      await _createImageCacheTable(db);
    }
  }

  Future<void> _createImageCacheTable(Database db) async {
    await db.execute('''
CREATE TABLE image_cache (
  url TEXT PRIMARY KEY,
  base64 TEXT NOT NULL
)
    ''');
  }

  Future<void> saveImage(String url, String base64) async {
    final db = await instance.database;
    await db.insert('image_cache', {
      'url': url,
      'base64': base64,
    }, conflictAlgorithm: ConflictAlgorithm.replace);
  }

  Future<String?> getImage(String url) async {
    final db = await instance.database;
    final List<Map<String, dynamic>> maps = await db.query(
      'image_cache',
      columns: ['base64'],
      where: 'url = ?',
      whereArgs: [url],
    );
    if (maps.isNotEmpty) {
      return maps.first['base64'] as String;
    }
    return null;
  }

  Future<void> deleteUnusedImages(List<String> activeUrls) async {
    final db = await instance.database;
    if (activeUrls.isEmpty) {
      await db.delete('image_cache');
      return;
    }

    // To handle large numbers of active URLs without hitting SQLite argument limits:
    // 1. Get all cached URLs.
    // 2. Identify which ones are NOT in the active list.
    // 3. Delete those specific URLs.

    final List<Map<String, dynamic>> result = await db.query(
      'image_cache',
      columns: ['url'],
    );
    final cachedUrls = result.map((r) => r['url'] as String).toSet();
    final activeUrlSet = activeUrls.toSet();

    final urlsToDelete = cachedUrls.difference(activeUrlSet).toList();

    const int batchSize = 900;
    for (var i = 0; i < urlsToDelete.length; i += batchSize) {
      final end = (i + batchSize < urlsToDelete.length)
          ? i + batchSize
          : urlsToDelete.length;
      final batch = urlsToDelete.sublist(i, end);
      final placeholders = List.filled(batch.length, '?').join(',');
      await db.delete(
        'image_cache',
        where: 'url IN ($placeholders)',
        whereArgs: batch,
      );
    }
  }

  Future<void> deleteImage(String url) async {
    final db = await instance.database;
    await db.delete('image_cache', where: 'url = ?', whereArgs: [url]);
  }

  Future<int> create(Note note) async {
    final db = await instance.database;
    final map = {
      'timestamp': note.timestamp,
      'data': jsonEncode(note.data),
      'service': note.service,
      'overview': note.overview,
      'image': note.image,
    };
    return await db.insert('notes', map);
  }

  Future<List<Note>> readAllNotes() async {
    final db = await instance.database;

    final orderBy = 'timestamp DESC';
    final result = await db.query('notes', orderBy: orderBy);

    return result.map((json) {
      final timestamp = json['timestamp'] as int;
      final service = json['service'] as String;

      return Note(
        timestamp: timestamp,
        data: jsonDecode(json['data'] as String),
        service: service,
        overview: json['overview'] as String,
        image: json['image'] as String?,
        // ID is not stored, so it will be auto-generated by constructor: '${timestamp}_$service'
        // or we can use rowid if we select it?
        // For now, let's respect the user's column list strictly.
      );
    }).toList();
  }

  Future<int> deleteOld(bool deleteOldData) async {
    // Implementation depends on requirements, for now simple delete all if needed
    // or delete based on timestamp
    return 0;
  }

  Future<void> deleteAll() async {
    final db = await instance.database;
    await db.delete('notes');
  }

  Future<void> deleteByService(String service) async {
    final db = await instance.database;
    await db.delete('notes', where: 'service = ?', whereArgs: [service]);
  }

  Future<void> insertBatch(List<Note> notes) async {
    final db = await instance.database;
    final batch = db.batch();
    for (var note in notes) {
      final map = {
        'timestamp': note.timestamp,
        'data': jsonEncode(note.data),
        'service': note.service,
        'overview': note.overview,
        'image': note.image,
      };
      batch.insert('notes', map);
    }
    await batch.commit(noResult: true);
  }

  Future<void> deleteWhere(String where, List<Object?> whereArgs) async {
    final db = await instance.database;
    await db.delete('notes', where: where, whereArgs: whereArgs);
  }
}
